
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('links/', views.linksToTables, name='links'),
    path('profile/', views.profile, name='profile'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('orders/create', views.OrderCreateView.as_view(), name='create_order'),
    path('orders/<int:pk>', views.OrderUpdateView.as_view(), name='orders_detail'),
    path('orders/<int:pk>/delete', views.OrderDeleteView.as_view(), name='delete_order'),
    path('trucks/', views.TruckListView.as_view(), name='trucks'),
    path('trucks/create', views.TruckCreateView.as_view(), name='create_truck'),
    path('trucks/<int:pk>', views.TruckUpdateView.as_view(), name='update_truck'),
    path('trucks/<int:pk>/delete', views.TruckDeleteView.as_view(), name='delete_truck'),
    path('trailers/', views.TrailerListView.as_view(), name='trailers'),
    path('trailers/create', views.TrailerCreateView.as_view(), name='create_trailer'),
    path('trailers/<int:pk>', views.TrailerUpdateView.as_view(), name='update_trailer'),
    path('trailers/<int:pk>/delete', views.TrailerDeleteView.as_view(), name='delete_trailer'),
    path('drivers/', views.DriverListView.as_view(), name='drivers'),
    path('drivers/create', views.DriverCreateView.as_view(), name='create_driver'),
    path('drivers/<int:pk>', views.DriverUpdateView.as_view(), name='update_driver'),
    path('drivers/<int:pk>/delete', views.DriverDeleteView.as_view(), name='delete_driver'),
    path('cargoes/', views.CargoesListView.as_view(), name='cargoes'),
    path('cargoes/create', views.CargoesCreateView.as_view(), name='create_cargo'),
    path('cargoes/<int:pk>', views.CargoesUpdateView.as_view(), name='update_cargo'),
    path('cargoes/<int:pk>/delete', views.CargoesDeleteView.as_view(), name='delete_cargo'),
    path('addresses/', views.AddressListView.as_view(), name='addresses'),
    path('addresses/create', views.AddressCreateView.as_view(), name='create_address'),
    path('addresses/<int:pk>', views.AddressUpdateView.as_view(), name='update_address'),
    path('addresses/<int:pk>/delete', views.AddressDeleteView.as_view(), name='delete_address'),
    path('customers/', views.CustomerListView.as_view(), name='customers'),
    path('customers/create', views.CustomerCreateView.as_view(), name='create_customer'),
    path('customers/<int:pk>', views.CustomerUpdateView.as_view(), name='update_customer'),
    path('customers/<int:pk>/delete', views.CustomerDeleteView.as_view(), name='delete_customer'),
    path('orderlines', views.OrderItemListView.as_view(), name='order_lines'),
    path('orderlines/create', views.OrderItemCreateView.as_view(), name='orderlines_create'),
    path('orderlines/<int:pk>', views.OrderItemDetailView.as_view(), name='orderlines_details'),
    path('orderlines/<int:pk>/update', views.OrderItemUpdateView.as_view(), name='orderlines_update'),
    path('orderlines/<int:pk>/delete', views.OrderItemDeleteView.as_view(), name='orderlines_delete'),
    path('uploads/', views.UploadsListView.as_view(), name='uploads'),
    path('uploads/create', views.UploadsCreateView.as_view(), name='add_file'),
    path('uploads/<int:pk>', views.delete_item, name='delete_item'),
]
